#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

printMessage "PUBLISH RELEASE ARTIFACTS"
export PGP_SECRET_RING=$HOME/.gnupg/play.gpg
sbt +publishSigned
# TODO: Uncomment before merge
#sbt bintrayRelease
#sbt sonatypeRelease